In [1]:
import pandas as pd
df = pd.read_csv("heart_disease.csv")
df.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   9971 non-null   float64
 1   Gender                9981 non-null   object
 2   Blood Pressure        9981 non-null   float64
 3   Cholesterol Level     9970 non-null   float64
 4   Exercise Habits       9975 non-null   object
 5   Smoking               9975 non-null   object
 6   Family Heart Disease  9979 non-null   object
 7   Diabetes              9970 non-null   object
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   object
 10  Low HDL Cholesterol   9975 non-null   object
 11  High LDL Cholesterol  9974 non-null   object
 12  Alcohol Consumption   9968 non-null   object
 13  Stress Level          9978 non-null   object
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption     9970 non-null   object
 16  Triglyceride Level    9974 non-null   float64
 17  Fasting Blood Sugar   9978 non-null   float64
 18  CRP Level             9974 non-null   float64
 19  Homocysteine Level    9980 non-null   float64
 20  Heart Disease Status  10000 non-null  object
dtypes: float64(9), object(12)
memory usage: 1.6+ MB

In [3]:
df['Age'].unique()

array([56., 69., 46., 32., 60., 25., 78., 38., 75., 36., 40., 28., 41.,
       70., 53., 57., 20., 39., 19., 61., 47., 55., 77., 50., 29., 42.,
       66., 44., 76., 80., 59., 45., 33., 79., 64., 68., 72., 74., 54.,
       24., 26., 35., 21., 31., 67., 43., 37., 52., 34., 23., 71., 51.,
       27., 48., 65., 62., 58., 18., 22., 30., 49., 73., 63., nan])

In [5]:
df['Heart Disease Status'].value_counts()

No     8000
Yes    2000
Name: Heart Disease Status, dtype: int64

In [4]:
df[df['Age'].isna()]

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
716,NaN,Male,160.0,184.0,Low,No,Yes,Yes,27.047567,Yes,...,Yes,None,Low,9.934741,High,350.0,150.0,11.272342,14.699716,No
1017,NaN,Male,173.0,251.0,Medium,No,No,No,22.763765,Yes,...,No,None,Medium,9.993930,Medium,280.0,159.0,14.503787,7.710791,No
1039,NaN,Female,154.0,274.0,High,No,Yes,No,35.849791,No,...,Yes,High,High,9.664409,Low,381.0,95.0,14.439670,14.609873,No
1468,NaN,Male,141.0,154.0,Medium,Yes,Yes,No,31.140165,No,...,Yes,Low,Low,6.201681,Low,329.0,137.0,12.462463,12.089437,No
1703,NaN,Male,147.0,258.0,High,Yes,Yes,No,35.350381,Yes,...,No,Low,High,8.594565,Low,323.0,96.0,11.595321,18.067759,No
1867,NaN,Male,142.0,225.0,High,Yes,No,Yes,23.275787,Yes,...,Yes,Low,Medium,6.317396,Low,329.0,85.0,7.686572,11.632494,No
2751,NaN,Male,142.0,167.0,Medium,Yes,Yes,Yes,39.995797,Yes,...,No,None,High,6.992129,Low,290.0,98.0,6.087670,17.357159,No
2869,NaN,Female,149.0,216.0,Low,Yes,No,No,22.739004,No,...,No,None,Low,8.105417,High,158.0,108.0,6.105748,18.420638,No
3195,NaN,Male,151.0,284.0,Medium,Yes,Yes,Yes,29.943396,No,...,No,Medium,Medium,9.378915,High,324.0,88.0,7.633548,13.992860,No
3265,NaN,Female,163.0,273.0,Medium,Yes,Yes,No,28.587588,Yes,...,Yes,Low,High,6.849657,Low,291.0,98.0,14.261332,6.605307,No
4071,NaN,Female,180.0,173.0,Medium,Yes,Yes,No,21.561825,No,...,Yes,Low,High,6.390804,Medium,210.0,124.0,7.838418,16.673293,No
4368,NaN,Male,167.0,188.0,High,Yes,No,No,24.582115,Yes,...,No,High,High,6.686355,Medium,192.0,92.0,12.657319,10.217309,No
4926,NaN,Male,125.0,198.0,Medium,Yes,No,No,22.952618,Yes,...,No,Low,High,4.381670,Low,207.0,150.0,3.562116,13.117695,No
5115,NaN,Female,179.0,256.0,High,No,No,No,35.562938,Yes,...,No,None,Low,6.955291,High,386.0,150.0,5.385226,10.895508,No
5151,NaN,Female,142.0,227.0,Low,No,No,No,18.830663,No,...,Yes,None,High,9.315764,Low,154.0,103.0,6.183026,5.967743,No
5396,NaN,Male,141.0,284.0,Medium,Yes,No,No,37.439024,Yes,...,Yes,Low,Medium,6.090322,Low,389.0,116.0,2.854775,11.296390,No
5857,NaN,Female,146.0,238.0,Medium,Yes,No,No,38.167391,No,...,No,High,Medium,9.726297,Medium,216.0,105.0,8.862839,19.282571,No
6143,NaN,Male,180.0,250.0,Low,Yes,Yes,No,22.749875,Yes,...,Yes,None,Medium,8.283050,High,104.0,91.0,3.102990,9.984202,No
6382,NaN,Male,145.0,201.0,High,No,No,No,36.778127,No,...,No,None,Low,4.114186,High,331.0,132.0,13.865621,5.178233,No
6477,NaN,Male,155.0,261.0,Low,No,No,Yes,38.986131,Yes,...,No,High,Medium,5.830971,Medium,370.0,150.0,14.419908,6.700846,No
6783,NaN,Female,148.0,158.0,High,Yes,Yes,Yes,39.177213,Yes,...,Yes,High,Medium,8.868347,High,124.0,86.0,10.926762,6.801805,No
7301,NaN,Female,120.0,169.0,High,Yes,No,Yes,25.504964,No,...,Yes,None,Low,5.916332,High,278.0,121.0,3.563080,6.087199,No
7527,NaN,Female,147.0,174.0,Medium,Yes,No,No,27.856518,Yes,...,Yes,None,Medium,4.687356,High,255.0,154.0,12.298738,13.056550,No
7728,NaN,Female,145.0,174.0,Medium,No,No,No,18.495778,Yes,...,No,High,Low,4.013310,High,333.0,122.0,2.373934,9.234120,No
7781,NaN,Male,170.0,297.0,High,Yes,Yes,Yes,29.746500,No,...,Yes,Medium,Medium,9.608564,High,198.0,152.0,1.236847,5.419517,No
8096,NaN,Female,167.0,255.0,Low,Yes,No,Yes,21.170543,Yes,...,Yes,High,Low,5.814622,Low,259.0,146.0,13.834235,6.571731,Yes
9192,NaN,Male,153.0,234.0,High,Yes,Yes,No,35.182266,Yes,...,No,Low,Low,7.083403,Low,387.0,122.0,9.533345,18.100440,Yes
9268,NaN,Female,139.0,184.0,High,No,No,Yes,39.398573,No,...,No,None,Low,5.868419,High,122.0,132.0,12.774543,9.703906,Yes
9835,NaN,Female,176.0,230.0,Low,Yes,Yes,No,30.283088,Yes,...,Yes,Medium,Medium,4.333238,Medium,191.0,158.0,11.919513,14.096972,Yes

In [5]:
df.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No

In [8]:
df.duplicated().count()

10000

In [9]:
df.tail(
)

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
9995,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,Yes,...,Yes,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,Yes
9996,38.0,Male,172.0,154.0,Medium,No,No,No,31.856801,Yes,...,Yes,None,High,8.247784,Low,377.0,83.0,2.658267,9.715709,Yes
9997,73.0,Male,152.0,201.0,High,Yes,No,Yes,26.899911,No,...,Yes,None,Low,4.436762,Low,248.0,88.0,4.408867,9.492429,Yes
9998,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,Yes,...,Yes,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,Yes
9999,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,No,...,Yes,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes